doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Order:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Order/Domain/Entity'
                prefix: 'App\Order\Domain\Entity'
                alias: App
            OrderValueObject:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Order/Domain/ValueObject'
                prefix: 'App\Order\Domain\ValueObject'
                alias: App
            Payment:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Payment/Domain/Entity'
                prefix: 'App\Payment\Domain\Entity'
                alias: App
            PaymentValueObject:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Payment/Domain/ValueObject'
                prefix: 'App\Payment\Domain\ValueObject'
                alias: App
            CommonValueObject:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Common/Domain/ValueObject'
                prefix: 'App\Common\Domain\ValueObject'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
