
product_list:
    path: /
    controller: \App\Product\Application\Controller\ProductController::list

# Order
order_create:
    path: /order/create
    controller: \App\Order\Application\Controller\OrderController::create

# Payment
payment_index:
    path: /payment/{orderId}
    controller: \App\Payment\Application\Controller\PaymentController::index